export default {
    homePage: {
        home: "Home",
        about: "About us",
        service: "Services",
        works: "How it works?",
        price: "Prices",
        review: "Reviews",
        contact: "Contact us",
        log: "Login",
        register: "Register",
        textHero: "Eat well, without overthinking. FoodHeaven does it for you.",
        textHero2: "Your week, your meals. Smart eating with FoodHeaven.",
        textAbout: "FoodHeaven is a web platform that transforms the way you\n" +
            "organize your weekly meals. Choose from a wide variety of\n" +
            "breakfast, lunch, and dinner options, customized to your\n" +
            "preferences, nutritional goals, and lifestyle. Simplify\n" +
            "your routine, eat better, and enjoy every bite.",
        plan: "Weekly Planning",
        textService: "Organize your weekly meals according to your nutritional needs and personal preferences.",
        plan2: "Custom Suppliers",
        textService2: "Connect with a diverse network of providers that fit your tastes and lifestyle.",
        plan3: "Nutritional Control",
        textService3: "Track your diet with a calorie counter and nutritional balance tailored to your goals.",
        plan4: "Home Delivery",
        textService4: "Receive your meals at your preferred time, directly to your home or office.",
        plan5: "Great quality",
        textService5: "We can boast of having great quality in both flavor and healthiness.",
        plan6: "Subscription Plans",
        textService6: "Choose from different monthly plans based on the number of meals and services you need.",
        works1: "Create your account",
        textWork: "Sign up quickly and easily from any device to access your personalized meal plan.",
        works2: "Configure your preferences",
        textWork2: "Indicate your tastes, dietary restrictions, and nutritional goals so the system can create the best plan for you.",
        works3: "Receive your Weekly Plan",
        textWork3: "Get a weekly menu tailored to your needs, including breakfast, lunch, and dinner, ready to plan.",
        works4: "Trusted Suppliers",
        textWork4: "We work with independent chefs and vetted local restaurants to ensure quality, flavor, and freshness in every meal.",
        works5: "Receive your meals",
        textWork5: "Enjoy your ready-made meals without cooking. We coordinate with suppliers and handle delivery.",
        works6: "Track Your Progress",
        textWork6: "Monitor your nutritional progress and adjust your plans according to your preferences.",
        month: "month",
        price1: "Standard Plan",
        planText1: "Includes daily lunch",
        planText2: "Nutritional control with calorie counter",
        planText3: "Full access to planning and deliveries",
        price2: "Early Plan",
        planText4: "Includes breakfast and lunch",
        price3: "Bajadón Plan",
        planText5: "Includes lunch and dinner",
        price4: "Full Plan",
        planText6: "Includes breakfast, lunch and dinner",
        planText7: "Priority customer support",
        choose: "Choose plan",
        terms: "This is the base price, prices may vary depending on the selection of dishes.",
        terms2: "There is the possibility of a dinner and breakfast plan at the same price as the \"Early\" plan.",
        review1: "Web Developer",
        reviewText: "As a time-poor professional, FoodHeaven has allowed me to organize my meals quickly and healthily, without worrying about planning. It's perfect for those of us with busy schedules!",
        review2: "Family Guy",
        reviewText2: "As a parent, I find it difficult to organize meals. FoodHeaven not only saves me time but also helps me plan healthy options for my family. Highly recommended!",
        review3: "Marketing Manager",
        reviewText3: "My job is demanding, and I always find it difficult to stay healthy. FoodHeaven helps me create a personalized, nutritious, and quick menu. It's everything I needed!",
        name: "Name",
        email: "Email",
        phone: "Phone Number",
        follow: "Follow us",
        info: "Legal information",
        advice: "Legal notice",
        policyPriv: "Privacy Policy",
        policyCook: "Cookie Policy",
        support: "Support",
        contactSupport: "Contact support",
        help: "Help Center",
        questions: "Frequently Asked Questions",
        rights: "All rights reserved."
    },
    toolbar: {
        title: "FoodHeaven",
        home: "Home",
        calendar: "Calendar",
        account: "Account"
    },
    calendar: {
        title: "Weekly Calendar",
        subtitle: "In this section, you can view your meals for each day",
        breakfast: "Breakfast",
        lunch: "Lunch",
        dinner: "Dinner",
        totalCalories: "Total calories:",
        totalWeekCalories: "Total weekly calories:",
        confirmButton: "Confirm plan",
        monday: "mon",
        tuesday: "tue",
        wednesday: "wed",
        thursday: "thu",
        friday: "fri",
        saturday: "sat",
        sunday: "sun",
        confirmText1: "Are you satisfied with your plan?",
        confirmText2: "Your plan has been successfully canceled",
        goHome: "Go to home",
        yes: "Yes",
        no: "No"
    },
    login: {
        title: "Login",
        subtitle: "Sign in with your preferred social network",
        email: "Enter your email address",
        password: "Password",
        button: "Login",
        forgot: "Can't log in?",
        forgotLink: "Forgot password",
        registerText: "Don't have an account?",
        or: "or",
        registerLink: "Register"
    },
    header: {
        title: "A menu designed for you",
        span: "schedule your meal",
        paragraph1: "Explore our menu ",
        paragraph2: "and place your orders quickly on our platform!"
    },

    cuadro: {
        title: "Meals available",
        text: "We have a variety of 20 different dishes in each food section: breakfast, lunch and dinner",
        dia1: "Monday",
        dia2: "Tuesday",
        dia3: "Wednesday",
        dia4: "Thursday",
        dia5: "Friday",
        dia6: "Saturday",
        dia7: "Sunday",
    },
    configuracion: {
        conf: "Configuration"
    },
    cuenta:{
        title: "Account",
        foto: "Change Photo",
        datos: "Personal Data",
        infodata: "FoodHeaven uses your information to verify your identity and protect our community",
        correo: "Mail",
        numero: "Cellphone Number",
        direccion: "Address",
    },
    pswsecu: {
        title: "Password and Security",
        descripcion: "Manage your passwords securely",
        cambiar: "Change Password",
        autenti: "Two-step authentication",
    },
    sus: {
        title: "Suscriptions",
        descripcion: "Manage your subscriptions",
        administrar: "Manage",
        verplan: "View Plan",
        suscri: "Cancel Subscription",
        last: "If you can still access your subscription until 08/25",
    },

    welcome: "!Welcome",
    plan: {
        full: "Plan: Full",
        change: "Change Plan"
    },
    subscription: {
        expires: "Your subscription expires in 45 days"
    },
    account: {
        name: "Name",
        email: "Email",
        phone: "Phone",
        city: "City",
        district: "District",
        address: "Address",
        config: "Settings"
    },
    register: {
        title: "Register",
        subtitle: "Register with your preferred social network",
        email: "Enter your email address",
        password: "Password",
        button: "Create Account",
        already: "Already have an account?",
        login: "Login",
        errorRequired: "All fields are required.",
        errorLength: "Password must be at least 6 characters.",
        success: "Registration successful.",
        or: "or"
    },
    title: {
        desayuno: "Breakfasts",
        almuerzo: "Lunches",
        cena: "Dinners",
    }
};
