export default {
    homePage: {
        home: "Inicio",
        about: "Acerca de",
        service: "Servicios",
        works: "¿Cómo funciona?",
        price: "Precios",
        review: "Reseñas",
        contact: "Contáctanos",
        log: "Iniciar Sesión",
        register: "Registrarse",
        textHero: "Come bien, sin pensar de más. FoodHeaven lo hace por ti.",
        textHero2: "Tu semana, tus platos. Alimentación inteligente con FoodHeaven.",
        textAbout: "FoodHeaven es una plataforma web que transforma la forma en que organizas tus comidas semanales. Elige entre una amplia variedad de opciones para desayuno, almuerzo y cena, personalizadas según tus preferencias, objetivos nutricionales y estilo de vida. Simplifica tu rutina, come mejor y disfruta cada bocado.",
        plan: "Planificación Semanal",
        textService: "Organiza tus comidas de la semana según tus necesidades nutricionales y preferencias personales.",
        plan2: "Proveedores Personalizados",
        textService2: "Conéctate con una red diversa de proveedores que se adaptan a tus gustos y estilo de vida.",
        plan3: "Control Nutricional",
        textService3: "Sigue tu dieta con un contador de calorías y balance nutricional adaptado a tus objetivos.",
        plan4: "Entrega a Domicilio",
        textService4: "Recibe tus comidas en el horario que prefieras, directamente en tu casa u oficina.",
        plan5: "Gran calidad",
        textService5: "Podemos presumir de tener gran calidad tanto en sabor como en salubridad.",
        plan6: "Planes de Suscripción",
        textService6: "Elige entre diferentes planes mensuales según la cantidad de comidas y servicios que necesitas.",
        works1: "Crea tu Cuenta",
        textWork: "Regístrate de manera rápida y fácil desde cualquier dispositivo para acceder a tu plan de comidas personalizado.",
        works2: "Configura tus Preferencias",
        textWork2: "Indica tus gustos, restricciones alimenticias, y objetivos nutricionales para que el sistema cree el mejor plan para ti.",
        works3: "Recibe tu Plan Semanal",
        textWork3: "Obtén un menú semanal adaptado a tus necesidades, incluyendo desayuno, almuerzo y cena, listo para planificar.",
        works4: "Proveedores de Confianza",
        textWork4: "Trabajamos con cocineros independientes y restaurantes locales verificados para garantizar calidad, sabor y frescura en cada comida.",
        works5: "Recibe tus Comidas",
        textWork5: "Disfruta tus platos listos sin cocinar. Nosotros coordinamos con los proveedores y nos encargamos de la entrega.",
        works6: "Rastrea tu Progreso",
        textWork6: "Monitorea tu progreso nutricional y ajusta tus planes según tus preferencias.",
        month: "mes",
        price1: "Plan Estándar",
        planText1: "Incluye almuerzo diario",
        planText2: "Control nutricional con contador de calorías",
        planText3: "Acceso completo a planificación y entregas",
        price2: "Plan Tempranero",
        planText4: "Incluye desayuno y almuerzo",
        price3: "Plan Bajadón",
        planText5: "Incluye almuerzo y cena",
        price4: "Plan Full",
        planText6: "Incluye desayuno, almuerzo y cena",
        planText7: "Soporte al cliente prioritario",
        choose: "Elegir plan",
        terms: "Es el precio base, los precios pueden variar de acuerdo a la selección de platos",
        terms2: "Hay la posibilidad de un plan cena y desayuno al mismo precio que el \"Tempranero\"",
        review1: "Desarrolladora Web",
        reviewText: "Como profesional con poco tiempo, FoodHeaven me ha permitido organizar mis comidas de manera rápida y saludable, sin preocuparme por planificar. ¡Es perfecto para quienes tenemos una agenda llena!",
        review2: "Padre de Familia",
        reviewText2: "Como padre de familia, me resulta difícil organizar las comidas. FoodHeaven no solo me ahorra tiempo, sino que también me ayuda a planificar opciones saludables para mi familia. ¡Muy recomendable!",
        review3: "Gerente de Marketing",
        reviewText3: "Mi trabajo es demandante y siempre me resulta difícil mantenerme saludable. FoodHeaven me ayuda a tener un menú personalizado, nutritivo y rápido. ¡Es todo lo que necesitaba!",
        name: "Nombre",
        email: "Correo",
        phone: "Número",
        follow: "Siguenos",
        info: "Información legal",
        advice: "Aviso legal",
        policyPriv: "Política de privacidad",
        policyCook: "Política de cookies",
        support: "Soporte",
        contactSupport: "Contacto con soporte",
        help: "Centro de ayuda",
        questions: "Preguntas frecuentes",
        rights: "Todos los derechos reservados."
    },
    toolbar: {
        title: "FoodHeaven",
        home: "Inicio",
        calendar: "Calendario",
        account: "Cuenta"
    },
    calendar: {
        title: "Calendario Semanal",
        subtitle: "En este apartado podras visualizar tus comidas de cada día",
        breakfast: "Desayuno",
        lunch: "Almuerzo",
        dinner: "Cena",
        totalCalories: "Calorías totales:",
        totalWeekCalories: "Calorías totales de la semana:",
        confirmButton: "Confirmar plan",
        monday: "lun",
        tuesday: "mar",
        wednesday: "mie",
        thursday: "jue",
        friday: "vie",
        saturday: "sab",
        sunday: "dom",
        confirmText1: "¿Estás conforme con su plan?",
        confirmText2: "Su plan ha sido cancelado con exito",
        goHome: "Ir a inicio",
        yes: "Sí",
        no: "No"
    },
    login: {
        title: "Iniciar sesión",
        subtitle: "Ingrese con su red social preferida",
        email: "Ingrese su correo electrónico",
        password: "Contraseña",
        button: "Iniciar sesión",
        forgot: "¿No puedes iniciar sesión?",
        forgotLink: "Olvidé mi contraseña",
        registerText: "¿Aún no tiene una cuenta?",
        or: "ó",
        registerLink: "Regístrate"
    },
    header: {
        title: "Un menú diseñado para ti",
        span: "programa tu comida",
        paragraph1: "¡Explora nuestro menú, ",
        paragraph2: "y realiza tus pedidos de manera rápida en nuestro plataforma!"

    },

    cuadro: {
        title: "Comidas disponibles",
        text: "Disponemos de una variedad de 20 platos distintos en cada sección de comida: desayuno, almuerzo y cena",
        dia1: "Lunes",
        dia2: "Martes",
        dia3: "Miércoles",
        dia4: "Jueves",
        dia5: "Viernes",
        dia6: "Sábado",
        dia7: "Domingo",
    },
    configuracion: {
        conf: "Configuración"
    },
    cuenta: {
        title: "Cuenta",
        foto: "Cambiar foto",
        datos: "Datos Personales",
        infodata: "FoodHeaven utiliza su información para verificar su identidad y proteger a nuestra comunidad",
        correo: "Correo",
        numero: "Número",
        direccion: "Direccion",
    },
    pswsecu: {
        title: "Contraseña y Seguridad",
        descripcion: "Administra tus contraseñas de forma segura",
        cambiar: "Cambiar Contraseña",
        autenti: "Autenticación en dos pasos",
    },

    sus: {
        title: "Suscripciones",
        descripcion: "Administre sus suscrpiciones",
        administrar: "Administrar",
        verplan: "Ver Plan",
        suscri: "Cancelar Suscripcion",
        last: "Si cancela ahora aún podrá acceder a su suscripcion hasta el 25/06",
    },
    welcome: "¡Bienvenido",
    plan: {
        full: "Plan: Full",
        change: "Cambiar Plan"
    },
    subscription: {
        expires: "Tu suscripción vence en 45 días"
    },
    account: {
        name: "Nombre",
        email: "Correo",
        phone: "Teléfono",
        city: "Ciudad",
        district: "Distrito",
        address: "Dirección",
        config: "Configuración"
    },
    register: {
        title: "Regístrate",
        subtitle: "Regístrate con tu red social preferida",
        email: "Ingrese su correo electrónico",
        password: "Contraseña",
        button: "Crear cuenta",
        already: "¿Ya tienes una cuenta?",
        login: "Iniciar sesión",
        errorRequired: "Todos los campos son obligatorios.",
        errorLength: "La contraseña debe tener al menos 6 caracteres.",
        success: "Registro exitoso.",
        or: "ó"
    },
    title: {
        desayuno: "Desayunos",
        almuerzo: "Almuerzos",
        cena: "Cenas",
    }
};
